-- STEP 7: inventory automation + payment tracking
-- Run after Step 6 SQL.

alter table public.products add column if not exists reserved_stock integer default 0;
alter table public.orders add column if not exists payment_status text default 'unpaid';
alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists cancelled_at timestamptz;

alter table public.orders
  drop constraint if exists orders_payment_status_check;
alter table public.orders
  add constraint orders_payment_status_check
  check (payment_status in ('unpaid','pending','paid','failed','refunded'));

-- Inventory movement ledger.
create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  order_id uuid references public.orders(id) on delete set null,
  change_qty integer not null,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.inventory_movements enable row level security;

drop policy if exists "admins inventory movements" on public.inventory_movements;
create policy "admins inventory movements"
on public.inventory_movements
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create index if not exists inventory_movements_product_idx
  on public.inventory_movements(product_id, created_at desc);

-- Trusted checkout transaction.
-- This function re-checks stock and price, creates the order + items,
-- and decrements stock atomically.
create or replace function public.place_order_secure(
  p_customer_id uuid,
  p_customer_name text,
  p_customer_phone text,
  p_customer_address text,
  p_customer_city text,
  p_payment_method text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_total numeric := 0;
  v_line_price numeric;
begin
  if auth.uid() is null or auth.uid() <> p_customer_id then
    raise exception 'Not authorized';
  end if;

  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart is empty';
  end if;

  -- Lock products while validating stock/prices.
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select * into v_product
    from public.products
    where id = (v_item->>'product_id')::uuid
      and active = true
    for update;

    if not found then
      raise exception 'Product unavailable';
    end if;

    v_qty := greatest(1, (v_item->>'quantity')::integer);

    if v_product.stock is not null and v_product.stock < v_qty then
      raise exception 'Insufficient stock for %', v_product.name;
    end if;

    v_line_price := coalesce(v_product.price, 0) * v_qty;
    v_total := v_total + v_line_price;
  end loop;

  insert into public.orders(
    customer_id, total, status, payment_method, payment_status,
    customer_name, customer_phone, customer_address, customer_city
  )
  values (
    p_customer_id, v_total, 'pending', lower(p_payment_method), 'unpaid',
    p_customer_name, p_customer_phone, p_customer_address, p_customer_city
  )
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select * into v_product
    from public.products
    where id = (v_item->>'product_id')::uuid
    for update;

    v_qty := greatest(1, (v_item->>'quantity')::integer);

    insert into public.order_items(order_id, product_id, quantity, price)
    values (v_order_id, v_product.id, v_qty, v_product.price);

    if v_product.stock is not null then
      update public.products
      set stock = stock - v_qty
      where id = v_product.id;

      insert into public.inventory_movements(product_id, order_id, change_qty, reason)
      values (v_product.id, v_order_id, -v_qty, 'order');
    end if;
  end loop;

  return v_order_id;
end;
$$;

revoke all on function public.place_order_secure(uuid,text,text,text,text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.place_order_secure(uuid,text,text,text,text,text,jsonb)
  to authenticated;

-- Admins can mark an order paid/refunded/cancelled.
-- Inventory restoration is intentionally kept as an explicit admin/server action
-- so accidental status changes do not silently alter stock.
